### PR TITLE
Updates dependencies to avoid graphql collisions

### LINKED ISSUE #24: GraphQL dependency collides with our own version
`graphql` is listed within the `peerDependencies` but also in the `dependencies`:

```
  "dependencies": {
    "graphql": "^14.4.0",
    "merge-graphql-schemas": "^1.5.8"
  },
  "peerDependencies": {
    "graphql": "^0.13.0 || ^14.0.0"
  },
```

It makes [the `GraphQLSchema` instance check fail](https://github.com/EasyGraphQL/easygraphql-parser/blob/6425e9a686/lib/schemaParser.js#L218-L220) since my schema was built with my `graphql` dependency and the check is made against another instance of `GraphQLSchema`, namely, the nested `graphql` dependency.

Removing the `node_modules/easygraphql-parser/node_modules` directory makes it work.

Would it be possible to move the `"graphql": "^14.4.0",` to `devDependencies` in this package? It would still work for development, and would avoid any collision in the wild.

### PR DESCRIPTION
**Pull request by emileber**
Fixes #24

### CODE REVIEW

**Comment by emileber** [comment]
Ok, when updating the package-lock, some minor versions have changed and now Istanbul only sees 91% coverage, without any changes in the code...

**Comment by estrada9166** [comment]
Thanks for this PR, can you change the coverage to 91% so we can merge this one!

**Comment by emileber** [comment]
Yes, doing it today.

**Comment by emileber** [comment]
Should be good now!

**Comment by estrada9166** [comment]
Thanks!!

**Comment by emileber** [comment]
It would be really great if a new release was created and if https://github.com/EasyGraphQL/easygraphql-load-tester was updated to use it (and released as well).

**Comment by estrada9166** [comment]
@emileber there's a new release now with these changes! Thanks! (For the parser and also for the load-tester package as well)

**Pull request merged**
